---
abstract: 'Binary Data Conversion using C Types'
author:
  - 'Marcus Holland-Moritz <mhx@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Convert-Binary-C
no_index:
  directory:
    - t
    - inc
    - support
  file:
    - bin/elf.PL
resources:
  homepage: http://search.cpan.org/~mhx/Convert-Binary-C/
  license: http://dev.perl.org/licenses/
  repository: https://github.com/mhx/Convert-Binary-C.git
  x_MailingList: convert-binary-c@yahoogroups.com
version: 0.78
