--- #YAML:1.0
name:                Convert-Binary-C
version:             0.65
abstract:            Binary Data Conversion using C Types
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_02
author:              Marcus Holland-Moritz <mhx@cpan.org>
distribution_type:   module
requires:     
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
no_index:
    directory:
        - support
    file:
        - bin/elf.PL
