--- #YAML:1.0
name:               Convert-Binary-C
version:            0.72
abstract:           Binary Data Conversion using C Types
author:
    - Marcus Holland-Moritz <mhx@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.49_01
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
